name: Run Test

on:
  push:
    branches: ["staging", "main"]
  pull_request:
    branches: ["staging", "main"]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install root Dependencies
        run: npm install

      - name: Install all server dependencies
        run: npm run install:all

      - name: Run build for TS bundle
        working-directory: server
        run: npm run build

      - name: Run server test
        working-directory: server
        run: npm test

      - name: Run client test
        working-directory: client
        run: npm test
        
      

